# Generated by Django 4.1 on 2024-10-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
    ]
