# Generated by Django 4.1 on 2024-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
