# Generated by Django 4.1 on 2024-12-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_replied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
