# Generated by Django 4.1 on 2024-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_last_delivered_contact_last_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='bg_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='bg_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='template_key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
