# Generated by Django 4.1 on 2024-12-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_alter_contact_template_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="template_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
