# Generated by Django 4.1 on 2025-01-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_template_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='customField',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
