# Generated by Django 4.1 on 2025-01-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenant", "0005_tenant_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsappCampaign",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("bpid", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("account_id", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.JSONField(blank=True, null=True)),
                (
                    "templates_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.tenant",
                    ),
                ),
            ],
        ),
    ]
