# Generated by Django 4.1 on 2024-10-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('whatsapp_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappTenantData',
            fields=[
                ('business_phone_number_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('flow_data', models.JSONField()),
                ('adj_list', models.JSONField()),
                ('access_token', models.CharField(max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_account_id', models.BigIntegerField()),
                ('start', models.IntegerField()),
                ('fallback_count', models.IntegerField()),
                ('fallback_message', models.CharField(max_length=1000)),
                ('flow_name', models.CharField(max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
        ),
    ]
