# Generated by Django 4.1 on 2024-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_chat', '0002_whatsapptenantdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapptenantdata',
            name='adj_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptenantdata',
            name='fallback_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptenantdata',
            name='fallback_message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptenantdata',
            name='flow_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptenantdata',
            name='flow_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapptenantdata',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
