# Generated by Django 4.1 on 2024-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_chat', '0003_alter_whatsapptenantdata_adj_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptenantdata',
            name='spreadsheet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
