# Generated by Django 4.1 on 2024-12-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_chat", "0004_whatsapptenantdata_spreadsheet_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="id",
            field=models.IntegerField(default=0),
        ),
    ]
