# Generated by Django 4.1 on 2024-12-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "whatsapp_chat",
            "0006_alter_whatsapptenantdata_business_phone_number_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="language",
            field=models.CharField(default="en", max_length=20),
        ),
    ]
