# Generated by Django 4.1 on 2024-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_chat", "0008_whatsapptenantdata_introductory_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="whatsapptenantdata",
            name="introductory_msg",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
