# Generated by Django 4.1 on 2024-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_chat", "0009_alter_whatsapptenantdata_introductory_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptenantdata",
            name="multilingual",
            field=models.BooleanField(default=False),
        ),
    ]
