# Generated by Django 4.1 on 2025-01-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_chat", "0010_whatsapptenantdata_multilingual"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageStatistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, null=True)),
                ("sent", models.IntegerField(default=0)),
                ("delivered", models.IntegerField(default=0)),
                ("read", models.IntegerField(default=0)),
                ("replied", models.IntegerField(default=0)),
                ("failed", models.IntegerField(default=0)),
                ("tenant_id", models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
