# Generated by Django 4.1 on 2025-01-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_chat", "0012_messagestatistics_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualMessageStatistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message_id", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("read", "Read"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("replied", "Replied"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("campaign", "Campaign"),
                            ("template", "Template"),
                            ("group", "Broadcast Group"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "type_identifier",
                    models.CharField(
                        help_text="Identifier based on the type: Campaign ID, Template Name, or Group ID.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the template (if applicable).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "userPhone",
                    models.CharField(
                        help_text="User's phone number in international format.",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        help_text="ID of the tenant associated with this message.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "bpid",
                    models.CharField(
                        help_text="Business process ID associated with the message.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the message record was created.",
                    ),
                ),
            ],
        ),
    ]
