# Generated by Django 4.1 on 2024-10-10 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CLTV',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
