# Generated by Django 4.1 on 2024-10-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='spreadsheet_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
