# Generated by Django 4.1 on 2024-11-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_spreadsheet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='catalog_id',
            field=models.BigIntegerField(default=234),
            preserve_default=False,
        ),
    ]
