# Generated by Django 4.1 on 2024-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_tenant_catalog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
