# Generated by Django 4.1 on 2025-01-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0005_tenant_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("basic", "Basic"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                default="free",
                max_length=20,
            ),
        ),
    ]
