# Generated by Django 4.1 on 2025-02-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0006_tenant_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="agents",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
