# Generated by Django 4.1 on 2024-10-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_conversation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
