# Generated by Django 4.1 on 2024-11-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_delete_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='message_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
