# Generated by Django 4.1 on 2024-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_alter_conversation_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
