# Generated by Django 4.1 on 2024-10-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_conversation_platform_alter_conversation_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
