# Generated by Django 4.1 on 2024-10-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('catalogue_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Catalog',
                'verbose_name_plural': 'Catalogs',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('image_link', models.URLField(unique=True)),
                ('condition', models.CharField(choices=[('new', 'new'), ('refurbished', 'refurbished'), ('used', 'used')], default='new', max_length=255)),
                ('availability', models.CharField(choices=[('in stock', 'in stock'), ('out of stock', 'out of stock')], default='in stock', max_length=255)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.catalog')),
            ],
        ),
    ]
