# Generated by Django 4.1 on 2024-10-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'in_stock'), ('out_of_stock', 'out_of_stock')], default='in stock', max_length=255),
        ),
    ]
