# Generated by Django 4.1 on 2024-10-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('shop', '0002_alter_products_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
        ),
    ]
