# Generated by Django 4.1 on 2024-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_link',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
