# Generated by Django 4.1 on 2024-10-25 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_products_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.catalog'),
        ),
    ]
