# Generated by Django 4.1 on 2024-12-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_products_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image_link",
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name="products",
            name="product_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="products",
            constraint=models.UniqueConstraint(
                fields=("product_id", "tenant"), name="unique_product_id_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="products",
            constraint=models.UniqueConstraint(
                fields=("title", "tenant"), name="unique_title_per_tenant"
            ),
        ),
    ]
