# Generated by Django 4.1 on 2024-12-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_remove_products_unique_product_id_per_tenant_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="products",
            name="unique_product_id_per_tenant",
        ),
        migrations.AddConstraint(
            model_name="products",
            constraint=models.UniqueConstraint(
                fields=("id", "tenant"), name="unique_id_per_tenant"
            ),
        ),
    ]
