# Generated by Django 4.1 on 2025-02-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0006_tenant_tier"),
        ("facebook_flows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flows",
            name="tenant",
            field=models.ForeignKey(
                default="ai",
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
            preserve_default=False,
        ),
    ]
