# Generated by Django 4.1 on 2025-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook_flows", "0002_flows_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flows",
            name="id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
