# Generated by Django 4.1 on 2025-01-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("amount", models.IntegerField()),
                ("currency", models.CharField(max_length=5)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("plan_id", models.CharField(max_length=50)),
                ("plan_name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("authenticated", "Authenticated"),
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("halted", "Halted"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("current_start", models.DateTimeField(blank=True, null=True)),
                ("current_end", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.JSONField(blank=True, max_length=15, null=True)),
                ("charge_at", models.DateTimeField(blank=True, null=True)),
                ("start_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                ("auth_attempts", models.IntegerField(default=0)),
                ("total_count", models.IntegerField(default=1)),
                ("paid_count", models.IntegerField(default=0)),
                ("remaining_count", models.IntegerField()),
                ("customer_notify", models.BooleanField(default=True)),
                ("created_at", models.BigIntegerField()),
                ("expire_by", models.BigIntegerField()),
                ("short_url", models.URLField(blank=True, max_length=255, null=True)),
                ("has_scheduled_changes", models.BooleanField(default=False)),
                ("change_scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="api", max_length=20)),
                ("offer_id", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
