# Generated by Django 4.1 on 2025-01-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="interval",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
