# Generated by Django 4.1 on 2025-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_plan_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
