# Generated by Django 4.1 on 2025-01-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_plan_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="auth_attempts",
        ),
    ]
