# Generated by Django 4.1 on 2025-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_remove_subscription_auth_attempts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expire_by",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
