# Generated by Django 4.1 on 2025-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_alter_subscription_expire_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
