# Generated by Django 4.1 on 2025-01-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_plan_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="tenant",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
