# Generated by Django 4.1 on 2025-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscription_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="past_payments",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expire_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
