# Generated by Django 4.1 on 2025-01-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscription_past_payments_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription2",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("tenant", models.CharField(max_length=10)),
                ("past_payments", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
