# Generated by Django 4.1 on 2024-10-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='model_name',
            field=models.CharField(choices=[('account', 'Account'), ('calls', 'calls'), ('lead', 'Lead'), ('interaction', 'Interaction'), ('contact', 'Contact')], max_length=20),
        ),
    ]
