# Generated by Django 4.1 on 2024-10-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0002_alter_customfield_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='model_name',
            field=models.CharField(choices=[('contact', 'Contact')], max_length=20),
        ),
    ]
