# Generated by Django 4.1 on 2025-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
