# Generated by Django 4.1 on 2025-01-06 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0005_tenant_key"),
        ("orders", "0002_alter_order_order_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="retailer",
        ),
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.tenant",
            ),
        ),
    ]
